// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAX3_jusr5YEuRWhabsUym6XQvNmWugao',
    appId: '1:818985157187:web:cb5ab228f65af5fe108af6',
    messagingSenderId: '818985157187',
    projectId: 'proyecto-6c537',
    authDomain: 'proyecto-6c537.firebaseapp.com',
    storageBucket: 'proyecto-6c537.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtlIoZQdKUbPDVZdlMKo3NH6XAYovyfVI',
    appId: '1:818985157187:android:253fd5a1573ff2e5108af6',
    messagingSenderId: '818985157187',
    projectId: 'proyecto-6c537',
    storageBucket: 'proyecto-6c537.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdXlCd-gx0nB3rjHK24Jt05wXI45iLLks',
    appId: '1:818985157187:ios:3783f61c756c1452108af6',
    messagingSenderId: '818985157187',
    projectId: 'proyecto-6c537',
    storageBucket: 'proyecto-6c537.firebasestorage.app',
    iosClientId: '818985157187-fu7ur5b0u8rrf18gjinuii1sf4o61hh0.apps.googleusercontent.com',
    iosBundleId: 'com.parking.app.iteso',
  );

}